---
- name: Create Kubernetes Cluster with kOps
  hosts: k8s
  become: yes
  vars_files:
    - vars.yml
  environment:
    KOPS_STATE_STORE: "{{ kops_state_store }}"
  tasks:
    - name: Export cluster config
      shell: |
        kops create cluster \
          --name {{ kops_cluster_name }} \
          --cloud aws \
          --zones {{ zones }} \
          --master-size {{ master_size }} \
          --node-size {{ node_size }} \
          --node-count {{ node_count }} \
          --yes \
          --state {{ kops_state_store }} \
          --dns private \
          --topology private
      args:
        creates: "/home/ec2-user/.kube/config"

    - name: Wait for cluster to be ready
      shell: |
        sleep 120
        until kops validate cluster --state {{ kops_state_store }}; do
          echo "Waiting for cluster to be ready..."
          sleep 30
        done
