---
- name: Create Kubernetes cluster with KOPS
  hosts: k8s_workers
  become: yes
  strategy: free  # Better for parallel execution
  vars_files:
    - group_vars/all.yml
  vars:
    ssh_key_path: "~/.ssh/id_rsa.pub"
    kops_version: "1.28.0"
    kops_download_path: "/usr/local/bin/kops"

  tasks:
    - name: Verify system connectivity
      ping:
      register: ping_test
      until: ping_test.ping == "pong"
      retries: 5
      delay: 10
      ignore_errors: yes

    - name: Install required packages
      package:
        name:
          - curl
          - unzip
          - python3-pip
        state: present
      async: 300
      poll: 15

    - name: Install AWS CLI via pip
      pip:
        name: awscli
        state: present
      when: ansible_python.version.major == 3

    - name: Download KOPS with retry logic
      block:
        - name: Create temp directory
          file:
            path: /tmp/kops-install
            state: directory
            mode: '0755'

        - name: Download KOPS binary
          get_url:
            url: "https://github.com/kubernetes/kops/releases/download/v{{ kops_version }}/kops-linux-amd64"
            dest: /tmp/kops-install/kops
            mode: '0755'
            timeout: 60
            validate_certs: no
          register: download_result
          until: download_result is succeeded
          retries: 5
          delay: 15
          ignore_errors: yes

        - name: Install KOPS
          copy:
            src: /tmp/kops-install/kops
            dest: "{{ kops_download_path }}"
            remote_src: yes
            mode: '0755'
            owner: root
            group: root

        - name: Verify installation
          command: "{{ kops_download_path }} version"
          register: kops_ver
          changed_when: false

      rescue:
        - name: Clean up on failure
          file:
            path: /tmp/kops-install
            state: absent
          ignore_errors: yes

        - name: Retry the entire block
          include_tasks: "{{ playbook_dir }}/retry_block.yml"
          when: retry_block.attempts < 3
          vars:
            retry_block:
              attempts: "{{ (retry_block.attempts | default(0)) + 1 }}"

    - name: Configure cluster (run once)
      delegate_to: "{{ groups['k8s_workers'][0] }}"
      run_once: yes
      shell: |
        set -o pipefail
        export KOPS_STATE_STORE={{ state_store }}
        {{ kops_download_path }} create cluster \
          --name={{ cluster_name }} \
          --zones={{ zones|join(',') }} \
          --node-count={{ node_count }} \
          --node-size={{ node_size }} \
          --master-size={{ master_size }} \
          --ssh-public-key={{ ssh_key_path }} \
          --yes 2>&1 | tee /tmp/kops_create.log
      environment:
        AWS_DEFAULT_REGION: "{{ aws_region }}"
