---
- name: Create Kubernetes cluster with KOPS
  hosts: localhost
  vars_files:
    - group_vars/all.yml
  tasks:

    - name: Export KOPS state store environment variable
      set_fact:
        kops_env: "export KOPS_STATE_STORE={{ state_store }}"

    - name: Create Kubernetes cluster
      shell: |
        export KOPS_STATE_STORE=s3://{{ lookup('env', 'KOPS_BUCKET') | default('chibuzo-kops-state') }}
        /usr/local/bin/kops create cluster \
          --name=k8s-prod.k8s.local \
          --zones=us-east-2a,us-east-2b \
          --node-count=2 \
          --node-size=t3.medium \
          --master-size=t3.medium \
          --yes
      environment:
        AWS_DEFAULT_REGION: us-east-2


    - name: Validate the cluster
      shell: |
        {{ kops_env }} && kops validate cluster --name={{ cluster_name }} --wait 10m
      environment:
        KOPS_STATE_STORE: "{{ state_store }}"
