---
- name: Create Kubernetes Cluster with kOps
  hosts: k8s
  become: yes
  vars_files:
    - group_vars/all.yml
  environment:
    KOPS_STATE_STORE: "{{ kops_state_store }}"
  tasks:

    - name: Verify kOps binary exists
      stat:
        path: /usr/local/bin/kops
      register: kops_bin

    - name: Fail if kOps is not installed
      fail:
        msg: "kOps is not installed at /usr/local/bin/kops"
      when: not kops_bin.stat.exists

    - name: Debug: Show kOps binary info
      debug:
        msg: "kOps is installed at /usr/local/bin/kops"

    - name: Create Kubernetes Clu
