---
- name: Create Kubernetes Cluster with kOps
  hosts: k8s
  become: yes
  vars_files:
    - group_vars/all.yml
  environment:
    KOPS_STATE_STORE: "{{ kops_state_store }}"
  tasks:

    - name: "Verify kOps binary exists"
      stat:
        path: /usr/local/bin/kops
      register: kops_bin

    - name: "Fail if kOps is not installed"
      fail:
        msg: "kOps is not installed at /usr/local/bin/kops"
      when: not kops_bin.stat.exists

    - name: "Debug: Show kOps binary info"
      debug:
        msg: "kOps is installed at /usr/local/bin/kops"

    - name: "Check if Kops cluster already exists"
    shell: "/usr/local/bin/kops get cluster --name {{ kops_cluster_name }} --state {{ kops_state_store }}"
    register: kops_cluster_check
    ignore_errors: yes
    
    - name: "Create Kubernetes Cluster (only if not exists)"
    shell: |
    /usr/local/bin/kops create cluster \
      --name {{ kops_cluster_name }} \
      --cloud aws \
      --zones {{ zones }} \
      --master-size {{ master_size }} \
      --node-size {{ node_size }} \
      --node-count {{ node_count }} \
      --yes \
      --state {{ kops_state_store }} \
      --dns private \
      --topology private
    when: kops_cluster_check.rc != 0
