---
- name: Delete Kubernetes cluster
  hosts: localhost
  vars_files:
    - group_vars/all.yml
  tasks:

    - name: Export KOPS state store environment variable
      set_fact:
        kops_env: "export KOPS_STATE_STORE={{ state_store }}"

    - name: Delete cluster
      shell: |
        {{ kops_env }} && \
        kops delete cluster --name {{ cluster_name }} --yes
      environment:
        KOPS_STATE_STORE: "{{ state_store }}"
