---
- name: Delete Kubernetes Cluster with kOps
  hosts: k8s
  become: yes
  vars_files:
    - group_vars/all.yml
  environment:
    KOPS_STATE_STORE: "{{ kops_state_store }}"

  tasks:

    - name: "Verify kOps binary exists"
      stat:
        path: /usr/local/bin/kops
      register: kops_bin

    - name: "Fail if kOps is not installed"
      fail:
        msg: "kOps is not installed at /usr/local/bin/kops"
      when: not kops_bin.stat.exists

    - name: "Check if kOps cluster exists"
      shell: >
        /usr/local/bin/kops get cluster
        --name {{ kops_cluster_name }}
        --state {{ kops_state_store }}
      register: kops_cluster_check
      ignore_errors: true
      environment:
        KOPS_STATE_STORE: "{{ kops_state_store }}"

    - name: "Delete cluster if it exists"
      shell: >
        /usr/local/bin/kops delete cluster
        --name {{ kops_cluster_name }}
        --state {{ kops_state_store }}
        --yes
      when: kops_cluster_check.rc == 0
      environment:
        KOPS_STATE_STORE: "{{ kops_state_store }}"

    - name: "Notify if cluster was not found"
      debug:
        msg: "Cluster {{ kops_cluster_name }} not found — skipping delete."
      when: kops_cluster_check.rc != 0

    - name: "Display stdout from deletion"
      debug:
        var: delete_output.stdout_lines
    
    - name: "Display stderr from deletion"
      debug:
        var: delete_output.stderr_lines
