---
- name: Delete Kubernetes Cluster
  hosts: k8s
  become: yes
  vars_files:
    - group_vars/all.yml
  environment:
    KOPS_STATE_STORE: "{{ kops_state_store }}"
  tasks:
    - name: Delete cluster
      shell: kops delete cluster --name {{ kops_cluster_name }} --yes



