---
- name: Install kOps and kubectl
  hosts: k8s
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install base packages
      yum:
        name:
          - unzip
          - wget
          - curl
          - jq
          - git
        state: present

    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl && mv kubectl /usr/local/bin/
      args:
        creates: /usr/local/bin/kubectl

    - name: Install kOps
      shell: |
        curl -Lo kops https://github.com/kubernetes/kops/releases/download/v1.27.0/kops-linux-amd64
        chmod +x kops && mv kops /usr/local/bin/
      args:
        creates: /usr/local/bin/kops

    - name: Verify kOps
      command: kops version
