---
- hosts: build_servers
  become: yes
  tasks:
    - name: Install Amazon Linux extras
      command: amazon-linux-extras install -y java-openjdk11

    - name: Install Maven and build tools
      yum:
        name:
          - maven
          - git
          - unzip
        state: present

- hosts: tomcat_servers
  become: yes
  tasks:
    - name: Install Amazon Linux extras
      command: amazon-linux-extras install -y java-openjdk11


    - name: Install Tomcat components
      yum:
        name:
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps
        state: present

    - name: Configure Tomcat service
      service:
        name: tomcat
        state: started
        enabled: yes
