apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-app
  labels:
    app: calc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-app
  template:
    metadata:
      labels:
        app: calc-app
    spec:
      containers:
        - name: calc-app
          image: chibuzone/calc-app:TAG  # <-- This line gets replaced by Jenkins
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
